---
framework: mocha
preRun:
     command:
        - yarn
preMerge:
  pattern:
    - "./test/unit/node/index.js"
postMerge:
  pattern:
    - "./test/unit/node/index.js"
postRun:
     command:
        - node --version
configFile: mocharc.yml
nodeVersion: 16.0.0
version: 1.0
