---
framework: mocha
preRun:
     command:
        - yarn
        - yarn --frozen-lockfile --network-timeout 180000
preMerge:
  pattern:
    - "./test/unit/node/index.js"
postMerge:
  pattern:
    - "./test/unit/node/index.js"
postRun:
     command:
        - node --version
configFile: mocharc.yml
version: 1.0
